// neuctra-authix-package/src/vue/components/ChangePasswordModal.vue
<template>
  <div
    v-if="isOpen"
    class="modal-overlay"
    :style="overlayStyle"
  >
    <div
      class="change-password-modal"
      :style="modalStyle"
    >
      <!-- Header -->
      <div class="modal-header">
        <div class="header-content">
          <div
            class="icon-container"
            :style="iconContainerStyle"
          >
            <Lock :size="20" />
          </div>
          <div>
            <h3 :style="titleStyle">Change Password</h3>
          </div>
        </div>
        <button
          @click="onClose"
          aria-label="Close password change modal"
          class="close-button"
          :style="closeButtonStyle"
          @mouseover="handleCloseHover"
          @mouseout="handleCloseLeave"
        >
          <X :size="20" />
        </button>
      </div>

      <!-- Form -->
      <form @submit="handleSubmit">
        <div
          v-for="field in passwordFields"
          :key="field.field"
          class="password-field"
        >
          <label
            :for="field.field"
            class="field-label"
            :style="labelStyle"
          >
            {{ field.label }}
          </label>
          <div class="input-wrapper">
            <div class="input-icon">
              <component :is="field.iconComponent" :size="18" />
            </div>
            <input
              :type="showPassword[field.field] ? 'text' : 'password'"
              :id="field.field"
              :name="field.field"
              :placeholder="`Enter ${field.label.toLowerCase()}`"
              v-model="formData[field.field]"
              @input="handleInput"
              class="password-input"
              :style="getInputStyle(field.field)"
              @focus="handleInputFocus"
              @blur="handleInputBlur(field.field, $event)"
            />
            <button
              type="button"
              @click="toggleVisibility(field.field)"
              class="visibility-toggle"
              :style="visibilityButtonStyle"
              @mouseover="handleVisibilityHover"
              @mouseout="handleVisibilityLeave"
            >
              <EyeOff v-if="showPassword[field.field]" :size="18" />
              <Eye v-else :size="18" />
            </button>
          </div>
          <div
            v-if="errors[field.field]"
            class="error-message"
            :style="errorStyle"
          >
            <span style="font-size: 16px">⚠</span>
            {{ errors[field.field] }}
          </div>
        </div>

        <!-- Actions -->
        <div
          class="modal-actions"
          :class="{ 'mobile-layout': isMobile }"
        >
          <button
            type="button"
            @click="onClose"
            :disabled="loading"
            class="cancel-button"
            :style="cancelButtonStyle"
            @mouseover="handleCancelHover"
            @mouseout="handleCancelLeave"
          >
            Cancel
          </button>
          <button
            type="submit"
            :disabled="loading"
            class="submit-button"
            :style="submitButtonStyle"
            @mouseover="handleSubmitHover"
            @mouseout="handleSubmitLeave"
          >
            <Loader2
              v-if="loading"
              :size="16"
              class="spinner"
            />
            {{ loading ? 'Updating...' : 'Update Password' }}
          </button>
        </div>
      </form>
    </div>
  </div>
</template>

<script setup>
import { ref, computed, onMounted, onUnmounted } from 'vue'
import { Lock, X, Eye, EyeOff, Loader2, Key } from 'lucide-vue-next'
import axios from 'axios'

const props = defineProps({
  isOpen: Boolean,
  onClose: Function,
  onSuccess: Function,
  onError: Function,
  userId: String,
  colors: Object
})

const formData = ref({
  currentPassword: '',
  newPassword: '',
  confirmPassword: ''
})
const errors = ref({})
const loading = ref(false)
const showPassword = ref({
  currentPassword: false,
  newPassword: false,
  confirmPassword: false
})
const isMobile = ref(false)

const passwordFields = [
  {
    field: 'currentPassword',
    label: 'Current Password',
    iconComponent: Key
  },
  {
    field: 'newPassword',
    label: 'New Password',
    iconComponent: Lock
  },
  {
    field: 'confirmPassword',
    label: 'Confirm Password',
    iconComponent: Lock
  }
]

// Styles
const overlayStyle = computed(() => ({
  position: 'fixed',
  inset: '0',
  background: 'rgba(0,0,0,0.7)',
  backdropFilter: 'blur(6px)',
  display: 'flex',
  alignItems: 'center',
  justifyContent: 'center',
  padding: '16px',
  zIndex: '1000'
}))

const modalStyle = computed(() => ({
  backgroundColor: props.colors.surface,
  border: `1px solid ${props.colors.border}`,
  borderRadius: '16px',
  maxWidth: '440px',
  width: '100%',
  padding: '24px',
  boxShadow: '0 20px 60px rgba(0,0,0,0.4)',
  maxHeight: '90vh',
  overflowY: 'auto'
}))

const iconContainerStyle = computed(() => ({
  width: '40px',
  height: '40px',
  borderRadius: '10px',
  background: `linear-gradient(135deg, ${props.colors.accent}20, ${props.colors.accent}40)`,
  display: 'flex',
  alignItems: 'center',
  justifyContent: 'center',
  color: props.colors.accent,
  flexShrink: 0
}))

const titleStyle = computed(() => ({
  color: props.colors.textPrimary,
  margin: '0',
  fontSize: '18px',
  fontWeight: '600',
  lineHeight: '1.4'
}))

const closeButtonStyle = computed(() => ({
  background: 'transparent',
  border: 'none',
  color: props.colors.textTertiary,
  cursor: 'pointer',
  padding: '8px',
  borderRadius: '8px',
  flexShrink: 0,
  width: '36px',
  height: '36px',
  display: 'flex',
  alignItems: 'center',
  justifyContent: 'center'
}))

const labelStyle = computed(() => ({
  display: 'block',
  marginBottom: '8px',
  color: props.colors.textPrimary,
  fontSize: '14px',
  fontWeight: '500',
  lineHeight: '1.4'
}))

const getInputStyle = (field) => ({
  width: '100%',
  padding: '14px 48px 14px 44px',
  borderRadius: '10px',
  border: `1.5px solid ${errors.value[field] ? props.colors.error : props.colors.border}`,
  backgroundColor: 'transparent',
  color: props.colors.textPrimary,
  fontSize: '15px',
  outline: 'none',
  transition: 'all 0.2s ease',
  boxSizing: 'border-box'
})

const visibilityButtonStyle = computed(() => ({
  position: 'absolute',
  right: '14px',
  top: '50%',
  transform: 'translateY(-50%)',
  background: 'transparent',
  border: 'none',
  cursor: 'pointer',
  color: props.colors.textTertiary,
  padding: '4px',
  borderRadius: '4px',
  width: '32px',
  height: '32px',
  display: 'flex',
  alignItems: 'center',
  justifyContent: 'center'
}))

const errorStyle = computed(() => ({
  fontSize: '13px',
  color: props.colors.error,
  marginTop: '6px',
  display: 'flex',
  alignItems: 'center',
  gap: '6px'
}))

const cancelButtonStyle = computed(() => ({
  padding: '14px 24px',
  borderRadius: '10px',
  border: `1.5px solid ${props.colors.border}`,
  background: 'transparent',
  color: props.colors.textPrimary,
  fontSize: '14px',
  fontWeight: '500',
  cursor: loading.value ? 'not-allowed' : 'pointer',
  flex: isMobile.value ? 'none' : 1,
  minWidth: isMobile.value ? '100%' : '120px',
  opacity: loading.value ? 0.6 : 1,
  transition: 'all 0.2s ease'
}))

const submitButtonStyle = computed(() => ({
  padding: '14px 24px',
  borderRadius: '10px',
  border: 'none',
  background: `linear-gradient(135deg, ${props.colors.accent}, ${props.colors.accent}E6)`,
  color: '#fff',
  fontSize: '14px',
  fontWeight: '600',
  cursor: loading.value ? 'not-allowed' : 'pointer',
  flex: isMobile.value ? 'none' : 1,
  minWidth: isMobile.value ? '100%' : '140px',
  opacity: loading.value ? 0.8 : 1,
  display: 'flex',
  alignItems: 'center',
  justifyContent: 'center',
  gap: '8px',
  transition: 'all 0.2s ease',
  boxShadow: loading.value ? 'none' : `0 4px 12px ${props.colors.accent}40`
}))

// Methods
const checkMobile = () => {
  isMobile.value = window.innerWidth < 640
}

const handleInput = (event) => {
  const { name, value } = event.target
  formData.value[name] = value
  if (errors.value[name]) {
    errors.value[name] = ''
  }
}

const toggleVisibility = (field) => {
  showPassword.value[field] = !showPassword.value[field]
}

const handleInputFocus = (event) => {
  event.target.style.borderColor = props.colors.accent
  event.target.style.boxShadow = `0 0 0 3px ${props.colors.accent}20`
}

const handleInputBlur = (field, event) => {
  event.target.style.borderColor = errors.value[field] ? props.colors.error : props.colors.border
  event.target.style.boxShadow = 'none'
}

const handleCloseHover = (event) => {
  event.currentTarget.style.backgroundColor = props.colors.border
  event.currentTarget.style.color = props.colors.textPrimary
}

const handleCloseLeave = (event) => {
  event.currentTarget.style.backgroundColor = 'transparent'
  event.currentTarget.style.color = props.colors.textTertiary
}

const handleVisibilityHover = (event) => {
  event.currentTarget.style.backgroundColor = props.colors.border
  event.currentTarget.style.color = props.colors.textPrimary
}

const handleVisibilityLeave = (event) => {
  event.currentTarget.style.backgroundColor = 'transparent'
  event.currentTarget.style.color = props.colors.textTertiary
}

const handleCancelHover = (event) => {
  if (!loading.value) {
    event.currentTarget.style.backgroundColor = props.colors.border
    event.currentTarget.style.transform = 'translateY(-1px)'
  }
}

const handleCancelLeave = (event) => {
  if (!loading.value) {
    event.currentTarget.style.backgroundColor = 'transparent'
    event.currentTarget.style.transform = 'translateY(0)'
  }
}

const handleSubmitHover = (event) => {
  if (!loading.value) {
    event.currentTarget.style.transform = 'translateY(-1px)'
    event.currentTarget.style.boxShadow = `0 6px 20px ${props.colors.accent}60`
  }
}

const handleSubmitLeave = (event) => {
  if (!loading.value) {
    event.currentTarget.style.transform = 'translateY(0)'
    event.currentTarget.style.boxShadow = `0 4px 12px ${props.colors.accent}40`
  }
}

const validate = () => {
  const newErrors = {}
  if (!formData.value.currentPassword) newErrors.currentPassword = 'Current password is required'
  if (!formData.value.newPassword) newErrors.newPassword = 'New password is required'
  else if (formData.value.newPassword.length < 6) newErrors.newPassword = 'Password must be at least 6 characters'
  if (formData.value.newPassword !== formData.value.confirmPassword) newErrors.confirmPassword = 'Passwords do not match'
  
  errors.value = newErrors
  return Object.keys(newErrors).length === 0
}

const handleSubmit = async (event) => {
  event.preventDefault()
  if (!validate()) return

  loading.value = true
  try {
    // You'll need to implement getSdkConfig or pass it as a prop
    const { baseUrl, apiKey, appId } = getSdkConfig()
    
    const { data } = await axios.put(
      `${baseUrl}/users/change-password/${props.userId}`,
      {
        appId,
        currentPassword: formData.value.currentPassword,
        newPassword: formData.value.newPassword,
      },
      {
        headers: {
          'x-api-key': apiKey,
        },
      }
    )

    if (data.success) {
      props.onSuccess(data.message || 'Password updated successfully')
      formData.value = {
        currentPassword: '',
        newPassword: '',
        confirmPassword: '',
      }
      props.onClose()
    } else {
      props.onError(data.message || 'Failed to update password')
    }
  } catch (err) {
    props.onError(err.response?.data?.message || 'Something went wrong')
  } finally {
    loading.value = false
  }
}

// Lifecycle
onMounted(() => {
  checkMobile()
  window.addEventListener('resize', checkMobile)
})

onUnmounted(() => {
  window.removeEventListener('resize', checkMobile)
})
</script>

<style scoped>
.modal-header {
  display: flex;
  justify-content: space-between;
  align-items: flex-start;
  margin-bottom: 24px;
  gap: 12px;
}

.header-content {
  display: flex;
  align-items: center;
  gap: 12px;
  flex: 1;
}

.password-field {
  margin-bottom: 20px;
  position: relative;
}

.input-wrapper {
  position: relative;
}

.input-icon {
  position: absolute;
  left: 14px;
  top: 50%;
  transform: translateY(-50%);
  color: v-bind('colors.textTertiary');
  z-index: 2;
}

.modal-actions {
  display: flex;
  gap: 12px;
  flex-direction: row;
  justify-content: flex-end;
  align-items: stretch;
}

.spinner {
  animation: spin 1s linear infinite;
}

@keyframes spin {
  from { transform: rotate(0deg); }
  to { transform: rotate(360deg); }
}

.change-password-modal::-webkit-scrollbar {
  width: 6px;
}

.change-password-modal::-webkit-scrollbar-track {
  background: transparent;
}

.change-password-modal::-webkit-scrollbar-thumb {
  background: v-bind('colors.border');
  border-radius: 3px;
}

.change-password-modal::-webkit-scrollbar-thumb:hover {
  background: v-bind('colors.textTertiary');
}

/* Mobile responsiveness */
@media (max-width: 480px) {
  .change-password-modal {
    padding: 20px 16px;
    margin: 0;
    border-radius: 12px 12px 0 0;
    max-height: 85vh;
  }
  
  .mobile-layout {
    flex-direction: column-reverse;
  }
}

@media (max-width: 360px) {
  .change-password-modal {
    padding: 16px 12px;
  }
}
</style>

// neuctra-authix-package/src/react/components/ChangePasswordModal.tsx
import React, { useState, ChangeEvent, FormEvent } from "react";
import axios from "axios";
import { X, Loader2, Lock, Key, EyeOff, Eye } from "lucide-react";
import { getSdkConfig } from "../../sdk/config.js";

interface ThemeColors {
  background: string;
  surface: string;
  surfaceLight: string;
  surfaceLighter: string;
  textPrimary: string;
  textSecondary: string;
  textTertiary: string;
  accent: string;
  accentHover: string;
  success: string;
  error: string;
  border: string;
}

interface ChangePasswordModalProps {
  baseUrl: string;
  apiKey: string;
  appId: string;
  isOpen: boolean;
  onClose: () => void;
  onSuccess: (msg: string) => void;
  onError: (msg: string) => void;
  userId: string;
  colors: ThemeColors;
}

const ChangePasswordModal: React.FC<ChangePasswordModalProps> = ({
  isOpen,
  onClose,
  onSuccess,
  onError,
  userId,
  colors,
}) => {
  const { baseUrl, apiKey, appId } = getSdkConfig();
  const [formData, setFormData] = useState({
    currentPassword: "",
    newPassword: "",
    confirmPassword: "",
  });
  const [errors, setErrors] = useState<Record<string, string>>({});
  const [loading, setLoading] = useState(false);
  const [showPassword, setShowPassword] = useState<Record<string, boolean>>({
    currentPassword: false,
    newPassword: false,
    confirmPassword: false,
  });

  // Check mobile screen size
  const [isMobile, setIsMobile] = useState(false);

  React.useEffect(() => {
    if (typeof window === "undefined") return;

    const checkMobile = () => {
      setIsMobile(window.innerWidth < 640);
    };

    checkMobile();
    window.addEventListener("resize", checkMobile);
    return () => window.removeEventListener("resize", checkMobile);
  }, []);

  if (!isOpen) return null;

  const handleChange = (e: ChangeEvent<HTMLInputElement>) => {
    const { name, value } = e.target;
    setFormData((prev) => ({ ...prev, [name]: value }));
    if (errors[name]) setErrors((prev) => ({ ...prev, [name]: "" }));
  };

  const toggleVisibility = (field: string) => {
    setShowPassword((prev) => ({ ...prev, [field]: !prev[field] }));
  };

  const validate = () => {
    const newErrors: Record<string, string> = {};
    if (!formData.currentPassword)
      newErrors.currentPassword = "Current password is required";
    if (!formData.newPassword)
      newErrors.newPassword = "New password is required";
    else if (formData.newPassword.length < 6)
      newErrors.newPassword = "Password must be at least 6 characters";
    if (formData.newPassword !== formData.confirmPassword)
      newErrors.confirmPassword = "Passwords do not match";
    setErrors(newErrors);
    return Object.keys(newErrors).length === 0;
  };

  const handleSubmit = async (e: FormEvent) => {
    e.preventDefault();
    if (!validate()) return;

    setLoading(true);
    try {
      const { data } = await axios.put(
        `${baseUrl}/users/change-password/${userId}`,
        {
          appId,
          currentPassword: formData.currentPassword,
          newPassword: formData.newPassword,
        },
        {
          headers: {
            "x-api-key": apiKey,
          },
        }
      );

      if (data.success) {
        onSuccess(data.message || "Password updated successfully");
        setFormData({
          currentPassword: "",
          newPassword: "",
          confirmPassword: "",
        });
        onClose();
      } else {
        onError(data.message || "Failed to update password");
      }
    } catch (err: any) {
      onError(err.response?.data?.message || "Something went wrong");
    } finally {
      setLoading(false);
    }
  };

  const passwordFields = [
    {
      field: "currentPassword",
      label: "Current Password",
      icon: <Key size={18} />,
    },
    {
      field: "newPassword",
      label: "New Password",
      icon: <Lock size={18} />,
    },
    {
      field: "confirmPassword",
      label: "Confirm Password",
      icon: <Lock size={18} />,
    },
  ];

  return (
    <div
      style={{
        position: "fixed",
        inset: 0,
        background: "rgba(0,0,0,0.7)",
        backdropFilter: "blur(6px)",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        padding: "16px",
        zIndex: 1000,
      }}
    >
      <div
        style={{
          backgroundColor: colors.surface,
          border: `1px solid ${colors.border}`,
          borderRadius: "16px",
          maxWidth: "440px",
          width: "100%",
          padding: "24px",
          boxShadow: "0 20px 60px rgba(0,0,0,0.4)",
          maxHeight: "90vh",
          overflowY: "auto",
        }}
        className="change-password-modal"
      >
        {/* Header */}
        <div
          style={{
            display: "flex",
            justifyContent: "space-between",
            alignItems: "flex-start",
            marginBottom: "24px",
            gap: "12px",
          }}
        >
          <div
            style={{
              display: "flex",
              alignItems: "center",
              gap: "12px",
              flex: 1,
            }}
          >
            <div
              style={{
                width: "40px",
                height: "40px",
                borderRadius: "10px",
                background: `linear-gradient(135deg, ${colors.accent}20, ${colors.accent}40)`,
                display: "flex",
                alignItems: "center",
                justifyContent: "center",
                color: colors.accent,
                flexShrink: 0,
              }}
            >
              <Lock size={20} />
            </div>
            <div>
              <h3
                style={{
                  color: colors.textPrimary,
                  margin: 0,
                  fontSize: "18px",
                  fontWeight: 600,
                  lineHeight: "1.4",
                }}
              >
                Change Password
              </h3>
            </div>
          </div>
          <button
            onClick={onClose}
            aria-label="Close password change modal"
            style={{
              background: "transparent",
              border: "none",
              color: colors.textTertiary,
              cursor: "pointer",
              padding: "8px",
              borderRadius: "8px",
              flexShrink: 0,
              width: "36px",
              height: "36px",
              display: "flex",
              alignItems: "center",
              justifyContent: "center",
            }}
            onMouseOver={(e) => {
              e.currentTarget.style.backgroundColor = colors.border;
              e.currentTarget.style.color = colors.textPrimary;
            }}
            onMouseOut={(e) => {
              e.currentTarget.style.backgroundColor = "transparent";
              e.currentTarget.style.color = colors.textTertiary;
            }}
          >
            <X size={20} />
          </button>
        </div>

        {/* Form */}
        <form onSubmit={handleSubmit}>
          {passwordFields.map(({ field, label, icon }) => (
            <div
              key={field}
              style={{
                marginBottom: "20px",
                position: "relative",
              }}
            >
              <label
                htmlFor={field}
                style={{
                  display: "block",
                  marginBottom: "8px",
                  color: colors.textPrimary,
                  fontSize: "14px",
                  fontWeight: 500,
                  lineHeight: "1.4",
                }}
              >
                {label}
              </label>
              <div style={{ position: "relative" }}>
                <div
                  style={{
                    position: "absolute",
                    left: "14px",
                    top: "50%",
                    transform: "translateY(-50%)",
                    color: colors.textTertiary,
                    zIndex: 2,
                  }}
                >
                  {icon}
                </div>
                <input
                  type={showPassword[field] ? "text" : "password"}
                  id={field}
                  name={field}
                  placeholder={`Enter ${label.toLowerCase()}`}
                  value={formData[field as keyof typeof formData]}
                  onChange={handleChange}
                  style={{
                    width: "100%",
                    padding: "14px 48px 14px 44px",
                    borderRadius: "10px",
                    border: `1.5px solid ${
                      errors[field] ? colors.error : colors.border
                    }`,
                    backgroundColor: "transparent",
                    color: colors.textPrimary,
                    fontSize: "15px",
                    outline: "none",
                    transition: "all 0.2s ease",
                    boxSizing: "border-box",
                  }}
                  onFocus={(e) => {
                    e.target.style.borderColor = colors.accent;
                    e.target.style.boxShadow = `0 0 0 3px ${colors.accent}20`;
                  }}
                  onBlur={(e) => {
                    e.target.style.borderColor = errors[field]
                      ? colors.error
                      : colors.border;
                    e.target.style.boxShadow = "none";
                  }}
                />
                <button
                  type="button"
                  onClick={() => toggleVisibility(field)}
                  style={{
                    position: "absolute",
                    right: "14px",
                    top: "50%",
                    transform: "translateY(-50%)",
                    background: "transparent",
                    border: "none",
                    cursor: "pointer",
                    color: colors.textTertiary,
                    padding: "4px",
                    borderRadius: "4px",
                    width: "32px",
                    height: "32px",
                    display: "flex",
                    alignItems: "center",
                    justifyContent: "center",
                  }}
                  onMouseOver={(e) => {
                    e.currentTarget.style.backgroundColor = colors.border;
                    e.currentTarget.style.color = colors.textPrimary;
                  }}
                  onMouseOut={(e) => {
                    e.currentTarget.style.backgroundColor = "transparent";
                    e.currentTarget.style.color = colors.textTertiary;
                  }}
                >
                  {showPassword[field] ? (
                    <EyeOff size={18} />
                  ) : (
                    <Eye size={18} />
                  )}
                </button>
              </div>
              {errors[field] && (
                <div
                  style={{
                    fontSize: "13px",
                    color: colors.error,
                    marginTop: "6px",
                    display: "flex",
                    alignItems: "center",
                    gap: "6px",
                  }}
                >
                  <span style={{ fontSize: "16px" }}>⚠</span>
                  {errors[field]}
                </div>
              )}
            </div>
          ))}

          {/* Actions */}
          <div
            style={{
              display: "flex",
              gap: "12px",
              flexDirection: isMobile ? "column-reverse" : "row",
              justifyContent: "flex-end",
              alignItems: "stretch",
            }}
          >
            <button
              type="button"
              onClick={onClose}
              disabled={loading}
              style={{
                padding: "14px 24px",
                borderRadius: "10px",
                border: `1.5px solid ${colors.border}`,
                background: "transparent",
                color: colors.textPrimary,
                fontSize: "14px",
                fontWeight: 500,
                cursor: loading ? "not-allowed" : "pointer",
                flex: isMobile ? "none" : 1,
                minWidth: isMobile ? "100%" : "120px",
                opacity: loading ? 0.6 : 1,
                transition: "all 0.2s ease",
              }}
              onMouseOver={(e) => {
                if (!loading) {
                  e.currentTarget.style.backgroundColor = colors.border;
                  e.currentTarget.style.transform = "translateY(-1px)";
                }
              }}
              onMouseOut={(e) => {
                if (!loading) {
                  e.currentTarget.style.backgroundColor = "transparent";
                  e.currentTarget.style.transform = "translateY(0)";
                }
              }}
            >
              Cancel
            </button>
            <button
              type="submit"
              disabled={loading}
              style={{
                padding: "14px 24px",
                borderRadius: "10px",
                border: "none",
                background: `linear-gradient(135deg, ${colors.accent}, ${colors.accent}E6)`,
                color: "#fff",
                fontSize: "14px",
                fontWeight: 600,
                cursor: loading ? "not-allowed" : "pointer",
                flex: isMobile ? "none" : 1,
                minWidth: isMobile ? "100%" : "140px",
                opacity: loading ? 0.8 : 1,
                display: "flex",
                alignItems: "center",
                justifyContent: "center",
                gap: "8px",
                transition: "all 0.2s ease",
                boxShadow: loading ? "none" : `0 4px 12px ${colors.accent}40`,
              }}
              onMouseOver={(e) => {
                if (!loading) {
                  e.currentTarget.style.transform = "translateY(-1px)";
                  e.currentTarget.style.boxShadow = `0 6px 20px ${colors.accent}60`;
                }
              }}
              onMouseOut={(e) => {
                if (!loading) {
                  e.currentTarget.style.transform = "translateY(0)";
                  e.currentTarget.style.boxShadow = `0 4px 12px ${colors.accent}40`;
                }
              }}
            >
              {loading ? (
                <>
                  <Loader2
                    size={16}
                    style={{
                      animation: "spin 1s linear infinite",
                    }}
                  />
                  Updating...
                </>
              ) : (
                "Update Password"
              )}
            </button>
          </div>
        </form>

        {/* Inline CSS for animations */}
        <style>
          {`
            @keyframes spin {
              from { transform: rotate(0deg); }
              to { transform: rotate(360deg); }
            }
            
            .change-password-modal::-webkit-scrollbar {
              width: 6px;
            }
            
            .change-password-modal::-webkit-scrollbar-track {
              background: transparent;
            }
            
            .change-password-modal::-webkit-scrollbar-thumb {
              background: ${colors.border};
              border-radius: 3px;
            }
            
            .change-password-modal::-webkit-scrollbar-thumb:hover {
              background: ${colors.textTertiary};
            }
            
            /* Mobile responsiveness */
            @media (max-width: 480px) {
              .change-password-modal {
                padding: 20px 16px;
                margin: 0;
                border-radius: 12px 12px 0 0;
                max-height: 85vh;
              }
            }
            
            @media (max-width: 360px) {
              .change-password-modal {
                padding: 16px 12px;
              }
            }
          `}
        </style>
      </div>
    </div>
  );
};

export default ChangePasswordModal;
