// neuctra-authix-ui-components/src/react/UserSignUp.tsx
import React, { useState } from "react";
import { signupUser } from "../api/signup.js";
import {
  Eye,
  EyeOff,
  Mail,
  Lock,
  User,
  CheckCircle,
  AlertCircle,
  Loader,
  Phone,
  MapPin,
  Image,
  UserCheck,
  UserX,
  X,
  Plus,
} from "lucide-react";
import { getSdkConfig } from "../sdk/config.js";

interface SignupFormProps {
  // Customization options
  logoUrl?: string;
  title?: string;
  subtitle?: string;
  footerText?: string;
  primaryColor?: string;
  gradient?: string;
  darkMode?: boolean;

  // Customizable fields - users can choose which fields to show
  showPhone?: boolean;
  showAddress?: boolean;
  showAvatar?: boolean;
  showRole?: boolean;
  showStatus?: boolean;

  loginUrl?: string;
  onSuccess?: (user: any) => void;
  onError?: (error: any) => void;
  onClose?: () => void;
}

// Define the form data interface
interface FormData {
  name: string;
  email: string;
  password: string;
  isActive: boolean;
  role: string;
  phone?: string;
  address?: string;
  avatarUrl?: string;
}

export const UserSignUp: React.FC<SignupFormProps> = ({
  logoUrl,
  title = "Create Your Account",
  subtitle = "Join our platform today",
  footerText = "Secure authentication powered by Neuctra Authix",
  primaryColor = "#00C214",
  gradient = "linear-gradient(135deg, #22c55e, #00C214)",
  darkMode = true,

  // Field visibility props - all optional, default to false
  showPhone = false,
  showAddress = false,
  showAvatar = false,
  showRole = false,
  showStatus = false,

  loginUrl,
  onSuccess,
  onError,
  onClose,
}) => {
  const { baseUrl, apiKey, appId } = getSdkConfig();
  // Initialize form data with only the fields that will be shown
  const initialFormData: FormData = {
    name: "",
    email: "",
    password: "",
    isActive: true,
    role: "user",
    ...(showPhone && { phone: "" }),
    ...(showAddress && { address: "" }),
    ...(showAvatar && { avatarUrl: "" }),
  };

  const [formData, setFormData] = useState<FormData>(initialFormData);
  const [showPassword, setShowPassword] = useState(false);
  const [loading, setLoading] = useState(false);
  const [message, setMessage] = useState<{
    type: "success" | "error";
    text: string;
  } | null>(null);
  const [errors, setErrors] = useState<{
    name?: string;
    email?: string;
    password?: string;
  }>({});

  const isMobile =
    typeof window !== "undefined" ? window.innerWidth < 768 : false;

  // Dynamic colors based on darkMode prop
  const textColor = darkMode ? "#ffffff" : "#111827";
  const subTextColor = darkMode ? "#a1a1aa" : "#6b7280";
  const inputBg = darkMode ? "rgba(255,255,255,0.05)" : "rgba(0,0,0,0.02)";
  const inputBorder = darkMode ? "rgba(255,255,255,0.1)" : "rgba(0,0,0,0.1)";

  const handleChange = (
    e: React.ChangeEvent<HTMLInputElement | HTMLSelectElement>
  ) => {
    const { name, value } = e.target;
    setFormData((prev: FormData) => ({ ...prev, [name]: value }));
  };

  const handleToggle = () => {
    setFormData((prev: FormData) => ({ ...prev, isActive: !prev.isActive }));
  };

  const validateForm = () => {
    const newErrors: { name?: string; email?: string; password?: string } = {};
    if (!formData.name) newErrors.name = "Name is required";
    if (!formData.email) {
      newErrors.email = "Email is required";
    } else if (!/\S+@\S+\.\S+/.test(formData.email)) {
      newErrors.email = "Invalid email address";
    }
    if (!formData.password) {
      newErrors.password = "Password is required";
    } else if (formData.password.length < 6) {
      newErrors.password = "Password must be at least 6 characters";
    }
    setErrors(newErrors);
    return Object.keys(newErrors).length === 0;
  };

  const handleSignup = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!validateForm()) return;

    setLoading(true);
    setMessage(null);

    try {
      const userData = {
        ...formData,
        appId: appId,
      };

      const user = await signupUser(userData, { baseUrl, apiKey });
      setMessage({ type: "success", text: "Account created successfully" });
      if (onSuccess) onSuccess(user);
    } catch (err: any) {
      const errorMsg = err.message || "Signup failed";
      setMessage({ type: "error", text: errorMsg });
      if (onError) onError(err);
    } finally {
      setLoading(false);
    }
  };

  // Calculate if we should show two columns (only if we have enough fields and not on mobile)
  const shouldShowTwoColumns =
    !isMobile && (showPhone || showAddress || showRole || showStatus);

  // Responsive Styles
  const containerStyle: React.CSSProperties = {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    fontFamily:
      "'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
  };

  const modalStyle: React.CSSProperties = {
    backgroundColor: darkMode ? "#000000" : "#ffffff",
    borderRadius: isMobile ? "12px" : "12px",
    boxShadow: "0 25px 50px -12px rgba(0, 0, 0, 0.25)",
    width: "100%",
    maxWidth: shouldShowTwoColumns ? "900px" : "390px",
    display: "flex",
    flexDirection: "column",
    overflow: "hidden",
  };

  // Header - Vertical Centered
  const headerStyle: React.CSSProperties = {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    textAlign: "center",
    padding: isMobile ? "32px 24px 0px 24px" : "20px 32px 0px 32px",
  };

  const logoStyle: React.CSSProperties = {
    height: isMobile ? "48px" : "50px",
    width: isMobile ? "48px" : "50px",
    objectFit: "contain",
    marginBottom: isMobile ? "16px" : "20px",
    borderRadius: "12px",
  };

  const iconWrapperStyle: React.CSSProperties = {
    height: isMobile ? "60px" : "80px",
    width: isMobile ? "60px" : "80px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: `${primaryColor}20`,
    borderRadius: "16px",
    marginBottom: isMobile ? "16px" : "20px",
  };

  const titleStyle: React.CSSProperties = {
    fontSize: isMobile ? "24px" : "24px",
    fontWeight: 700,
    color: textColor,
    margin: "0 0 8px 0",
    letterSpacing: "-0.025em",
    lineHeight: "1.2",
  };

  const subtitleStyle: React.CSSProperties = {
    fontSize: isMobile ? "14px" : "14px",
    color: subTextColor,
    margin: 0,
    lineHeight: "1.5",
  };

  const closeButtonStyle: React.CSSProperties = {
    position: "absolute",
    top: isMobile ? "16px" : "20px",
    right: isMobile ? "16px" : "20px",
    color: subTextColor,
    backgroundColor: "transparent",
    border: "none",
    padding: "8px",
    borderRadius: "8px",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    transition: "all 0.2s ease",
  };

  const bodyStyle: React.CSSProperties = {
    flex: 1,
    padding: isMobile ? "24px" : "10px 32px",
  };

  const formStyle: React.CSSProperties = {
    display: "grid",
    gridTemplateColumns: shouldShowTwoColumns ? "1fr 1fr" : "1fr",
    gap: isMobile ? "20px" : "20px",
  };

  const columnStyle: React.CSSProperties = {
    display: "flex",
    justifyContent: "end",
    flexDirection: "column",
    gap: isMobile ? "16px" : "16px",
  };

  const fieldStyle: React.CSSProperties = {
    display: "flex",
    flexDirection: "column",
    gap: "4px",
  };

  const labelStyle: React.CSSProperties = {
    fontSize: isMobile ? "14px" : "14px",
    fontWeight: 600,
    color: textColor,
  };

  const inputWrapperStyle: React.CSSProperties = {
    position: "relative",
    display: "flex",
    alignItems: "center",
  };

  const inputIconStyle: React.CSSProperties = {
    position: "absolute",
    left: "16px",
    color: subTextColor,
    width: "20px",
    height: "20px",
  };

  const inputStyle: React.CSSProperties = {
    width: "100%",
    padding: isMobile ? "14px 14px 14px 48px" : "16px 16px 16px 52px",
    backgroundColor: inputBg,
    border: `1px solid ${inputBorder}`,
    borderRadius: "12px",
    color: textColor,
    fontSize: isMobile ? "15px" : "15px",
    outline: "none",
    transition: "all 0.2s ease",
  };

  const selectStyle: React.CSSProperties = {
    width: "100%",
    padding: isMobile ? "14px 48px 14px 16px" : "16px 52px 16px 16px",
    backgroundColor: inputBg,
    border: `1px solid ${inputBorder}`,
    borderRadius: "12px",
    color: textColor,
    fontSize: isMobile ? "16px" : "16px",
    outline: "none",
    appearance: "none",
  };

  const toggleButtonStyle: React.CSSProperties = {
    position: "absolute",
    right: "16px",
    backgroundColor: "transparent",
    border: "none",
    color: subTextColor,
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: "4px",
    borderRadius: "4px",
    transition: "all 0.2s ease",
  };

  // Avatar Preview at the top
  const avatarPreviewContainerStyle: React.CSSProperties = {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: "12px",
    margin: "10px 0px",
  };

  const avatarPreviewStyle: React.CSSProperties = {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: "12px",
    borderRadius: "16px",
    width: "100%",
    maxWidth: "200px",
  };

  const avatarImageStyle: React.CSSProperties = {
    width: "60px",
    height: "60px",
    borderRadius: "50%",
    objectFit: "cover",
    border: `2px solid ${primaryColor}30`,
  };

  const avatarPlaceholderStyle: React.CSSProperties = {
    width: "60px",
    height: "60px",
    borderRadius: "50%",
    backgroundColor: `${primaryColor}10`,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    color: primaryColor,
    border: `2px solid ${primaryColor}20`,
  };

  const statusToggleStyle: React.CSSProperties = {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "21px 20px",
    backgroundColor: inputBg,
    border: `1px solid ${inputBorder}`,
    borderRadius: "12px",
  };

  const statusContentStyle: React.CSSProperties = {
    display: "flex",
    alignItems: "center",
    gap: "12px",
    fontSize: "12px",
  };

  const toggleSwitchStyle: React.CSSProperties = {
    width: "52px",
    height: "28px",
    backgroundColor: formData.isActive ? primaryColor : "#9ca3af",
    borderRadius: "14px",
    position: "relative",
    cursor: "pointer",
    transition: "background-color 0.2s",
  };

  const toggleKnobStyle: React.CSSProperties = {
    position: "absolute",
    top: "2px",
    left: formData.isActive ? "26px" : "2px",
    width: "24px",
    height: "24px",
    backgroundColor: "#ffffff",
    borderRadius: "50%",
    transition: "left 0.2s",
    boxShadow: "0 2px 4px rgba(0,0,0,0.2)",
  };

  const footerStyle: React.CSSProperties = {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: "12px",
    padding: isMobile ? "0px 24px 18px 24px" : "14px 32px 18px 32px",
  };

  const footerTextStyle: React.CSSProperties = {
    fontSize: isMobile ? "12px" : "13px",
    color: subTextColor,
    textAlign: "center",
    lineHeight: "1.5",
  };

  const loginLinkStyle: React.CSSProperties = {
    color: "#ffffff",
    textDecoration: "none",
    fontSize: isMobile ? "14px" : "15px",
    fontWeight: 500,
    textAlign: "center",
  };

  const buttonContainerStyle: React.CSSProperties = {
    display: "flex",
    gap: "12px",
    width: "100%",
  };

  const buttonStyle: React.CSSProperties = {
    padding: isMobile ? "14px 20px" : "14px 24px",
    borderRadius: "12px",
    border: "none",
    fontSize: isMobile ? "15px" : "14px",
    fontWeight: 600,
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "8px",
    transition: "all 0.3s ease",
    flex: 1,
  };

  const cancelButtonStyle: React.CSSProperties = {
    ...buttonStyle,
    backgroundColor: inputBg,
    color: textColor,
    border: `1px solid ${inputBorder}`,
  };

  const submitButtonStyle: React.CSSProperties = {
    ...buttonStyle,
    background: loading ? "#9ca3af" : gradient,
    color: "#ffffff",
    boxShadow: loading ? "none" : `0 4px 14px 0 ${primaryColor}40`,
  };

  const disabledButtonStyle: React.CSSProperties = {
    ...buttonStyle,
    backgroundColor: "#9ca3af",
    color: "#ffffff",
    cursor: "not-allowed",
    boxShadow: "none",
  };

  const messageStyle: React.CSSProperties = {
    padding: "16px",
    borderRadius: "12px",
    fontSize: "14px",
    display: "flex",
    alignItems: "flex-start",
    gap: "12px",
    marginTop: "20px",
  };

  const successMessageStyle: React.CSSProperties = {
    ...messageStyle,
    backgroundColor: `${primaryColor}15`,
    border: `1px solid ${primaryColor}30`,
    color: primaryColor,
  };

  const errorMessageStyle: React.CSSProperties = {
    ...messageStyle,
    backgroundColor: "rgba(239, 68, 68, 0.1)",
    border: "1px solid rgba(239, 68, 68, 0.3)",
    color: "#ef4444",
  };

  return (
    <div style={containerStyle}>
      <div style={modalStyle}>
        {/* Header - Vertical Centered */}
        <div style={{ position: "relative" }}>
          <div style={headerStyle}>
            {logoUrl ? (
              <img src={logoUrl} alt="Logo" style={logoStyle} />
            ) : (
              <div style={iconWrapperStyle}>
                <User size={isMobile ? 32 : 40} color={primaryColor} />
              </div>
            )}

            <div>
              <h2 style={titleStyle}>{title}</h2>
              <p style={subtitleStyle}>{subtitle}</p>
            </div>
          </div>

          {onClose && (
            <button
              onClick={onClose}
              style={closeButtonStyle}
              onMouseOver={(e) => {
                e.currentTarget.style.backgroundColor = darkMode
                  ? "rgba(255,255,255,0.1)"
                  : "rgba(0,0,0,0.05)";
              }}
              onMouseOut={(e) => {
                e.currentTarget.style.backgroundColor = "transparent";
              }}
            >
              <X size={24} />
            </button>
          )}
        </div>

        {/* Body */}
        <div style={bodyStyle}>
          {/* Avatar Preview at the top */}
          {showAvatar && (
            <div style={avatarPreviewContainerStyle}>
              <div style={avatarPreviewStyle}>
                {formData.avatarUrl ? (
                  <img
                    src={formData.avatarUrl}
                    alt="Avatar Preview"
                    style={avatarImageStyle}
                    onError={(e) => {
                      const target = e.target as HTMLImageElement;
                      target.style.display = "none";
                    }}
                  />
                ) : (
                  <div style={avatarPlaceholderStyle}>
                    <User size={40} />
                  </div>
                )}
                <span
                  style={{
                    fontSize: "14px",
                    color: subTextColor,
                    fontWeight: 500,
                  }}
                >
                  Avatar Preview
                </span>
              </div>
            </div>
          )}
          <form onSubmit={handleSignup} style={formStyle}>
            {/* Left Column - Required fields + Phone/Address */}
            <div style={columnStyle}>
              {/* Name - Required */}
              <div style={fieldStyle}>
                <label style={labelStyle}>Full Name</label>
                <div style={inputWrapperStyle}>
                  <User size={20} style={inputIconStyle} />
                  <input
                    type="text"
                    name="name"
                    placeholder="Enter your full name"
                    value={formData.name}
                    onChange={handleChange}
                    style={inputStyle}
                    required
                  />
                </div>
                {errors.name && (
                  <span
                    style={{
                      color: "#ef4444",
                      fontSize: "14px",
                      marginTop: "4px",
                    }}
                  >
                    {errors.name}
                  </span>
                )}
              </div>

              {/* Email - Required */}
              <div style={fieldStyle}>
                <label style={labelStyle}>Email Address</label>
                <div style={inputWrapperStyle}>
                  <Mail size={20} style={inputIconStyle} />
                  <input
                    type="email"
                    name="email"
                    placeholder="Enter your email address"
                    value={formData.email}
                    onChange={handleChange}
                    style={inputStyle}
                    required
                  />
                </div>
                {errors.email && (
                  <span
                    style={{
                      color: "#ef4444",
                      fontSize: "14px",
                      marginTop: "4px",
                    }}
                  >
                    {errors.email}
                  </span>
                )}
              </div>

              {/* Password - Required */}
              <div style={fieldStyle}>
                <label style={labelStyle}>Password</label>
                <div style={inputWrapperStyle}>
                  <Lock size={20} style={inputIconStyle} />
                  <input
                    type={showPassword ? "text" : "password"}
                    name="password"
                    placeholder="Create a secure password"
                    value={formData.password}
                    onChange={handleChange}
                    style={inputStyle}
                    required
                  />
                  <button
                    type="button"
                    onClick={() => setShowPassword(!showPassword)}
                    style={toggleButtonStyle}
                    onMouseOver={(e) => {
                      e.currentTarget.style.backgroundColor = darkMode
                        ? "rgba(255,255,255,0.1)"
                        : "rgba(0,0,0,0.05)";
                    }}
                    onMouseOut={(e) => {
                      e.currentTarget.style.backgroundColor = "transparent";
                    }}
                  >
                    {showPassword ? <EyeOff size={20} /> : <Eye size={20} />}
                  </button>
                </div>
                {errors.password && (
                  <span
                    style={{
                      color: "#ef4444",
                      fontSize: "14px",
                      marginTop: "4px",
                    }}
                  >
                    {errors.password}
                  </span>
                )}
              </div>

              {/* Phone - Optional */}
              {showPhone && (
                <div style={fieldStyle}>
                  <label style={labelStyle}>Phone Number</label>
                  <div style={inputWrapperStyle}>
                    <Phone size={20} style={inputIconStyle} />
                    <input
                      type="tel"
                      name="phone"
                      placeholder="Enter your phone number"
                      value={formData.phone || ""}
                      onChange={handleChange}
                      style={inputStyle}
                    />
                  </div>
                </div>
              )}
            </div>

            {/* Right Column - Role and Status */}
            {shouldShowTwoColumns && (
              <div style={columnStyle}>
                {/* Address - Optional */}
                {showAddress && (
                  <div style={fieldStyle}>
                    <label style={labelStyle}>Address</label>
                    <div style={inputWrapperStyle}>
                      <MapPin size={20} style={inputIconStyle} />
                      <input
                        type="text"
                        name="address"
                        placeholder="Enter your address"
                        value={formData.address || ""}
                        onChange={handleChange}
                        style={inputStyle}
                      />
                    </div>
                  </div>
                )}

                {/* Avatar URL - At the bottom of first column */}
                {showAvatar && (
                  <div style={fieldStyle}>
                    <label style={labelStyle}>Avatar URL</label>
                    <div style={inputWrapperStyle}>
                      <Image size={20} style={inputIconStyle} />
                      <input
                        type="url"
                        name="avatarUrl"
                        placeholder="Paste your avatar image URL"
                        value={formData.avatarUrl || ""}
                        onChange={handleChange}
                        style={inputStyle}
                      />
                    </div>
                  </div>
                )}

                {/* Role - Optional */}
                {showRole && (
                  <div style={fieldStyle}>
                    <label style={labelStyle}>Role</label>
                    <div style={inputWrapperStyle}>
                      <select
                        name="role"
                        value={formData.role}
                        onChange={handleChange}
                        style={selectStyle}
                      >
                        <option value="user">User</option>
                        <option value="admin">Admin</option>
                        <option value="moderator">Moderator</option>
                      </select>
                    </div>
                  </div>
                )}

                {/* Status - Optional */}
                {showStatus && (
                  <div style={statusToggleStyle}>
                    <div style={statusContentStyle}>
                      {formData.isActive ? (
                        <UserCheck size={24} color={primaryColor} />
                      ) : (
                        <UserX size={24} color="#ef4444" />
                      )}
                      <div>
                        <div
                          style={{
                            fontSize: "14px",
                            fontWeight: 600,
                            color: textColor,
                          }}
                        >
                          Account Status
                        </div>
                        <div style={{ fontSize: "12px", color: subTextColor }}>
                          {formData.isActive
                            ? "User can access the system"
                            : "User account is disabled"}
                        </div>
                      </div>
                    </div>
                    <div
                      style={toggleSwitchStyle}
                      onClick={handleToggle}
                      onMouseOver={(e) => {
                        e.currentTarget.style.opacity = "0.8";
                      }}
                      onMouseOut={(e) => {
                        e.currentTarget.style.opacity = "1";
                      }}
                    >
                      <div style={toggleKnobStyle} />
                    </div>
                  </div>
                )}
              </div>
            )}

            {/* Role and Status for single column layout */}
            {!shouldShowTwoColumns && (
              <>
                {showRole && (
                  <div style={fieldStyle}>
                    <label style={labelStyle}>Role</label>
                    <div style={inputWrapperStyle}>
                      <select
                        name="role"
                        value={formData.role}
                        onChange={handleChange}
                        style={selectStyle}
                      >
                        <option value="user">User</option>
                        <option value="admin">Admin</option>
                        <option value="moderator">Moderator</option>
                      </select>
                    </div>
                  </div>
                )}

                {showStatus && (
                  <div style={statusToggleStyle}>
                    <div style={statusContentStyle}>
                      {formData.isActive ? (
                        <UserCheck size={24} color={primaryColor} />
                      ) : (
                        <UserX size={24} color="#ef4444" />
                      )}
                      <div>
                        <div
                          style={{
                            fontSize: "16px",
                            fontWeight: 600,
                            color: textColor,
                          }}
                        >
                          Account Status
                        </div>
                        <div style={{ fontSize: "14px", color: subTextColor }}>
                          {formData.isActive
                            ? "User can access the system"
                            : "User account is disabled"}
                        </div>
                      </div>
                    </div>
                    <div style={toggleSwitchStyle} onClick={handleToggle}>
                      <div style={toggleKnobStyle} />
                    </div>
                  </div>
                )}
              </>
            )}
          </form>

          {/* Messages */}
          {message && (
            <div
              style={
                message.type === "success"
                  ? successMessageStyle
                  : errorMessageStyle
              }
            >
              {message.type === "success" ? (
                <CheckCircle size={20} color={primaryColor} />
              ) : (
                <AlertCircle size={20} color="#ef4444" />
              )}
              <span style={{ fontWeight: 500 }}>{message.text}</span>
            </div>
          )}
        </div>

        {/* Footer */}
        <div style={footerStyle}>
          {loginUrl && (
            <a href={loginUrl} style={loginLinkStyle}>
              Already have an account?{" "}
              <span style={{ color: primaryColor }}>Sign in</span>
            </a>
          )}

          <div style={buttonContainerStyle}>
            {onClose && (
              <button
                type="button"
                onClick={onClose}
                style={cancelButtonStyle}
                onMouseOver={(e) => {
                  e.currentTarget.style.backgroundColor = darkMode
                    ? "rgba(255,255,255,0.1)"
                    : "rgba(0,0,0,0.05)";
                }}
                onMouseOut={(e) => {
                  e.currentTarget.style.backgroundColor = inputBg;
                }}
              >
                <X size={18} />
                Cancel
              </button>
            )}
            <button
              type="button"
              onClick={handleSignup}
              disabled={loading}
              style={loading ? disabledButtonStyle : submitButtonStyle}
              onMouseOver={(e) => {
                if (!loading) {
                  e.currentTarget.style.transform = "translateY(-2px)";
                  e.currentTarget.style.boxShadow = `0 6px 20px 0 ${primaryColor}60`;
                }
              }}
              onMouseOut={(e) => {
                if (!loading) {
                  e.currentTarget.style.transform = "translateY(0)";
                  e.currentTarget.style.boxShadow = `0 4px 14px 0 ${primaryColor}40`;
                }
              }}
            >
              {loading ? (
                <Loader
                  size={18}
                  style={{ animation: "spin 1s linear infinite" }}
                />
              ) : (
                <Plus size={18} />
              )}
              {loading ? "Creating..." : "Create Account"}
            </button>
          </div>
          {footerText && <p style={footerTextStyle}>{footerText}</p>}
        </div>
      </div>

      <style>
        {`
          @keyframes spin {
            from { transform: rotate(0deg); }
            to { transform: rotate(360deg); }
          }
          
          @media (max-width: 480px) {
            input, select {
              font-size: 16px !important;
            }
          }
        `}
      </style>
    </div>
  );
};

// neuctra-authix-package/src/vue/UserSignup.vue
<template>
  <div :style="containerStyle">
    <div :style="cardStyle">
      <!-- Header -->
      <div :style="headerStyle">
        <img
          v-if="logoUrl"
          :src="logoUrl"
          alt="Logo"
          :style="logoStyle"
        />
        <User
          v-else
          :size="40"
          :color="primaryColor"
          :style="userIconStyle"
        />
        <h2 :style="titleStyle">
          {{ title }}
        </h2>
        <p :style="subtitleStyle">
          {{ subtitle }}
        </p>
      </div>

      <!-- Avatar Preview -->
      <div
        v-if="showAvatar && formData.avatarUrl"
        :style="avatarPreviewStyle"
      >
        <img
          :src="formData.avatarUrl"
          alt="Avatar Preview"
          :style="avatarImageStyle"
          @error="handleAvatarError"
        />
      </div>

      <!-- Signup Form -->
      <form
        @submit.prevent="handleSignup"
        :style="formStyle"
      >
        <!-- Name -->
        <div :style="fieldStyle">
          <label
            for="signup-name"
            :style="labelStyle"
          >
            Full Name
          </label>
          <div :style="inputWrapperStyle">
            <User
              :size="20"
              :style="inputIconStyle"
            />
            <input
              id="signup-name"
              type="text"
              placeholder="Enter your full name"
              v-model="formData.name"
              @input="clearError('name')"
              :style="getNameInputStyle"
            />
          </div>
          <span
            v-if="errors.name"
            :style="errorTextStyle"
          >
            {{ errors.name }}
          </span>
        </div>

        <!-- Email -->
        <div :style="fieldStyle">
          <label
            for="signup-email"
            :style="labelStyle"
          >
            Email Address
          </label>
          <div :style="inputWrapperStyle">
            <Mail
              :size="20"
              :style="inputIconStyle"
            />
            <input
              id="signup-email"
              type="email"
              placeholder="Enter your email address"
              v-model="formData.email"
              @input="clearError('email')"
              :style="getEmailInputStyle"
            />
          </div>
          <span
            v-if="errors.email"
            :style="errorTextStyle"
          >
            {{ errors.email }}
          </span>
        </div>

        <!-- Password -->
        <div :style="fieldStyle">
          <label
            for="signup-password"
            :style="labelStyle"
          >
            Password
          </label>
          <div :style="inputWrapperStyle">
            <Lock
              :size="20"
              :style="inputIconStyle"
            />
            <input
              id="signup-password"
              :type="showPassword ? 'text' : 'password'"
              placeholder="Create a secure password"
              v-model="formData.password"
              @input="clearError('password')"
              :style="getPasswordInputStyle"
            />
            <button
              type="button"
              @click="showPassword = !showPassword"
              :style="toggleButtonStyle"
            >
              <EyeOff v-if="showPassword" :size="20" />
              <Eye v-else :size="20" />
            </button>
          </div>
          <span
            v-if="errors.password"
            :style="errorTextStyle"
          >
            {{ errors.password }}
          </span>
        </div>

        <!-- Avatar URL - Optional -->
        <div
          v-if="showAvatar"
          :style="fieldStyle"
        >
          <label
            for="signup-avatar"
            :style="labelStyle"
          >
            Avatar URL (Optional)
          </label>
          <div :style="inputWrapperStyle">
            <Image
              :size="20"
              :style="inputIconStyle"
            />
            <input
              id="signup-avatar"
              type="url"
              placeholder="Paste your avatar image URL"
              v-model="formData.avatarUrl"
              :style="inputStyle"
            />
          </div>
        </div>

        <!-- Links -->
        <div :style="linksStyle">
          <a
            v-if="loginUrl"
            :href="loginUrl"
            :style="linkStyle"
          >
            Already have an account?
          </a>
        </div>

        <!-- Submit -->
        <button
          type="submit"
          :disabled="loading"
          :style="submitButtonStyle"
        >
          <Loader
            v-if="loading"
            :size="18"
            :style="loaderStyle"
          />
          {{ loading ? 'Creating Account...' : 'Create Account' }}
        </button>
      </form>

      <!-- Messages -->
      <div
        v-if="message"
        :style="getMessageStyle(message.type)"
      >
        <CheckCircle
          v-if="message.type === 'success'"
          :size="20"
        />
        <AlertCircle
          v-else
          :size="20"
        />
        <span>{{ message.text }}</span>
      </div>

      <!-- Footer -->
      <div :style="footerStyle">
        {{ footerText }}
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, onMounted, onUnmounted, type CSSProperties } from 'vue'
import {
  Eye,
  EyeOff,
  Mail,
  Lock,
  User,
  CheckCircle,
  AlertCircle,
  Loader,
  Image,
} from 'lucide-vue-next'
import { signupUser } from '../api/signup.js'
import { getSdkConfig } from '../sdk/config.js'

interface SignupFormProps {
  // Customization options
  logoUrl?: string
  title?: string
  subtitle?: string
  footerText?: string
  primaryColor?: string
  gradient?: string
  darkMode?: boolean

  // Only avatar is optional
  showAvatar?: boolean

  loginUrl?: string
  onSuccess?: (user: any) => void
  onError?: (error: any) => void
}

interface FormData {
  name: string
  email: string
  password: string
  avatarUrl?: string
}

const props = withDefaults(defineProps<SignupFormProps>(), {
  title: 'Create Your Account',
  subtitle: 'Join our platform today',
  footerText: 'Secure authentication powered by Neuctra Authix',
  primaryColor: '#00C214',
  gradient: 'linear-gradient(135deg, #22c55e, #00C214)',
  darkMode: true,
  showAvatar: false,
})

const { baseUrl, apiKey, appId } = getSdkConfig()

// State
const formData = ref<FormData>({
  name: '',
  email: '',
  password: '',
  ...(props.showAvatar && { avatarUrl: '' }),
})
const showPassword = ref(false)
const loading = ref(false)
const message = ref<{
  type: 'success' | 'error'
  text: string
} | null>(null)
const errors = ref<{
  name?: string
  email?: string
  password?: string
}>({})

// Responsive
const isMobile = ref(false)

const checkMobile = () => {
  isMobile.value = window.innerWidth < 768
}

onMounted(() => {
  checkMobile()
  window.addEventListener('resize', checkMobile)
})

onUnmounted(() => {
  window.removeEventListener('resize', checkMobile)
})

// Theme
const textColor = computed(() => (props.darkMode ? '#ffffff' : '#111827'))
const subTextColor = computed(() => (props.darkMode ? '#a1a1aa' : '#6b7280'))
const inputBg = computed(() => (props.darkMode ? 'rgba(255,255,255,0.05)' : 'rgba(0,0,0,0.02)'))
const inputBorder = computed(() => (props.darkMode ? 'rgba(255,255,255,0.1)' : 'rgba(0,0,0,0.1)'))

// Handlers
const clearError = (field: keyof typeof errors.value) => {
  if (errors.value[field]) {
    errors.value = { ...errors.value, [field]: undefined }
  }
}

const validateForm = () => {
  const newErrors: { name?: string; email?: string; password?: string } = {}
  
  if (!formData.value.name.trim()) {
    newErrors.name = 'Name is required'
  }
  
  if (!formData.value.email.trim()) {
    newErrors.email = 'Email is required'
  } else if (!/\S+@\S+\.\S+/.test(formData.value.email)) {
    newErrors.email = 'Invalid email address'
  }
  
  if (!formData.value.password) {
    newErrors.password = 'Password is required'
  } else if (formData.value.password.length < 6) {
    newErrors.password = 'Password must be at least 6 characters'
  }
  
  errors.value = newErrors
  return Object.keys(newErrors).length === 0
}

const handleSignup = async (e: Event) => {
  e.preventDefault()
  if (!validateForm()) return

  loading.value = true
  message.value = null

  try {
    const userData = {
      ...formData.value,
      appId: appId,
    }

    const user = await signupUser(userData, { baseUrl, apiKey })
    message.value = { type: 'success', text: 'Account created successfully!' }
    props.onSuccess?.(user)
  } catch (err: any) {
    const errorMsg = err.message || 'Signup failed. Please try again.'
    message.value = { type: 'error', text: errorMsg }
    props.onError?.(err)
  } finally {
    loading.value = false
  }
}

const handleAvatarError = (e: Event) => {
  const target = e.target as HTMLImageElement
  target.style.display = 'none'
}

const getMessageStyle = (type: 'success' | 'error'): CSSProperties => ({
  marginTop: '16px',
  padding: '12px',
  borderRadius: '12px',
  fontSize: '14px',
  display: 'flex',
  alignItems: 'center',
  gap: '10px',
  backgroundColor: type === 'success'
    ? `${props.primaryColor}15`
    : 'rgba(239,68,68,0.1)',
  border: type === 'success'
    ? `1px solid ${props.primaryColor}30`
    : '1px solid rgba(239,68,68,0.3)',
  color: type === 'success' ? props.primaryColor : '#ef4444',
})

// Styles with proper TypeScript typing
const containerStyle: CSSProperties = {
  display: 'flex',
  justifyContent: 'center',
  alignItems: 'center',
}

const cardStyle = computed((): CSSProperties => ({
  minWidth: isMobile.value ? '320px' : '340px',
  width: '100%',
  maxWidth: '390px',
  display: 'flex',
  flexDirection: 'column',
  borderRadius: '10px',
  fontFamily: "'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
  backgroundColor: props.darkMode ? '#000000' : '#ffffff',
  padding: isMobile.value ? '30px 24px' : '32px 28px',
}))

const headerStyle: CSSProperties = {
  display: 'flex',
  flexDirection: 'column',
  alignItems: 'center',
  marginBottom: '20px',
}

const logoStyle: CSSProperties = {
  height: '50px',
  width: '50px',
  marginBottom: '10px',
}

const userIconStyle: CSSProperties = {
  marginBottom: '10px',
}

const titleStyle = computed((): CSSProperties => ({
  fontSize: '24px',
  fontWeight: 700,
  color: textColor.value,
  margin: '0',
}))

const subtitleStyle = computed((): CSSProperties => ({
  fontSize: '14px',
  color: subTextColor.value,
  margin: '6px 0 0 0',
}))

const avatarPreviewStyle: CSSProperties = {
  display: 'flex',
  justifyContent: 'center',
  marginBottom: '16px',
}

const avatarImageStyle: CSSProperties = {
  width: '60px',
  height: '60px',
  borderRadius: '50%',
  objectFit: 'cover',
  border: `2px solid ${props.primaryColor}30`,
}

const formStyle: CSSProperties = {
  display: 'flex',
  flexDirection: 'column',
  gap: '14px',
}

const fieldStyle: CSSProperties = {
  display: 'flex',
  flexDirection: 'column',
  gap: '4px',
}

const inputWrapperStyle: CSSProperties = {
  position: 'relative',
}

const inputIconStyle = computed((): CSSProperties => ({
  position: 'absolute',
  left: '14px',
  top: '50%',
  transform: 'translateY(-50%)',
  color: subTextColor.value,
}))

const inputStyle = computed((): CSSProperties => ({
  width: '100%',
  padding: isMobile.value ? '14px 14px 14px 44px' : '16px 16px 16px 44px',
  backgroundColor: inputBg.value,
  border: `1px solid ${inputBorder.value}`,
  borderRadius: '12px',
  color: textColor.value,
  fontSize: isMobile.value ? '15px' : '15px',
  outline: 'none',
  transition: 'all 0.2s ease',
  boxSizing: 'border-box',
}))

const getNameInputStyle = computed((): CSSProperties => ({
  ...inputStyle.value,
  borderColor: errors.value.name ? '#ef4444' : inputBorder.value,
}))

const getEmailInputStyle = computed((): CSSProperties => ({
  ...inputStyle.value,
  borderColor: errors.value.email ? '#ef4444' : inputBorder.value,
}))

const getPasswordInputStyle = computed((): CSSProperties => ({
  ...inputStyle.value,
  borderColor: errors.value.password ? '#ef4444' : inputBorder.value,
}))

const toggleButtonStyle: CSSProperties = {
  position: 'absolute',
  right: '14px',
  top: '50%',
  transform: 'translateY(-50%)',
  background: 'transparent',
  border: 'none',
  color: subTextColor.value,
  cursor: 'pointer',
  padding: '4px',
}

const linksStyle: CSSProperties = {
  display: 'flex',
  justifyContent: 'space-between',
  fontSize: '13px',
  marginTop: '6px',
}

const linkStyle = computed((): CSSProperties => ({
  color: props.primaryColor,
  textDecoration: 'none',
  fontWeight: 500,
}))

const submitButtonStyle = computed((): CSSProperties => ({
  padding: '12px',
  background: props.gradient,
  color: '#fff',
  border: 'none',
  borderRadius: '10px',
  fontWeight: 600,
  cursor: loading.value ? 'not-allowed' : 'pointer',
  opacity: loading.value ? 0.7 : 1,
  marginTop: '8px',
  display: 'flex',
  alignItems: 'center',
  justifyContent: 'center',
  gap: '8px',
}))

const loaderStyle: CSSProperties = {
  animation: 'spin 1s linear infinite',
}

const labelStyle = computed((): CSSProperties => ({
  fontSize: '14px',
  fontWeight: 500,
  color: textColor.value,
}))

const errorTextStyle: CSSProperties = {
  color: '#ef4444',
  fontSize: '12px',
  marginTop: '2px',
}

const footerStyle = computed((): CSSProperties => ({
  textAlign: 'center',
  fontSize: '12px',
  color: subTextColor.value,
  marginTop: '20px',
  padding: '0 4px',
}))
</script>

<style>
@keyframes spin {
  from { transform: rotate(0deg); }
  to { transform: rotate(360deg); }
}
</style>
